#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']

20.times do
  uri = URI.parse('http://dpltest-travisdpltest.boxfuse.io:8080/')
  actual = uri.read
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
