#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']

20.times do
  begin
    uri = URI.parse("https://bintray.com/dpl-test/dpl_test/download_file?file_path=dpl_test%2F#{ENV['ID']}%2Ftest")
    puts "Checking #{uri.to_s}"
    actual = uri.read
    puts "expected: #{expected.inspect}"
    puts "actual: #{actual.inspect}"
    exit 0 if actual == expected
  rescue OpenURI::HTTPError => e
    puts e.message
    sleep 5
  end
end

abort 'failed'
