#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']
url = "https://bintray.com/dpl-test/dpl_test/download_file?file_path=dpl_test%2F#{ENV['ID']}%2Ftest"

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

20.times do
  puts "Checking #{url}"
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
