#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

def run(cmd)
  puts "$ #{cmd}"
  system cmd
  abort "#{cmd} failed" unless $?.exitstatus == 0
end

def file(path, content)
  puts "Writing file #{path}"
  mkdir_p(File.dirname(path))
  File.write(path, content)
end

def cd(dir)
  mkdir_p(dir) unless dir == '..'
  chdir(dir)
end

cd 'tmp/dpl_test'

file 'lib/dpl/test.rb', <<~str
  module Dpl
    module Test
      extend self
      def test
        puts ENV['ID']
      end
    end
  end
str

file 'dpl_test.gemspec', <<~str
  Gem::Specification.new do |s|
    s.name        = 'dpl_test'
    s.version     = "0.0.#{ENV['TRAVIS_BUILD_NUMBER']}.dev-#{ENV['ID']}"
    s.licenses    = ['MIT']
    s.summary     = "This is dpl_test"
    s.description = "This is dpl_test."
    s.authors     = ["Travis CI Dpl"]
    s.email       = 'contact@travis-ci.com'
    s.homepage    = 'https://github.org/travis-ci/dpl'
    s.files       = ["lib/dpl/test.rb"]
  end
str

run 'gem build dpl_test.gemspec'
