#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = ENV['ID']
url = "https://packagecloud.io/api/v1/repos/dpl-test/dpl-test/package/gem/dpl_test/0.0.#{ENV['TRAVIS_BUILD_NUMBER']}.dev.pre.#{ENV['ID']}.json"

def poll(url)
  URI.parse(url).read(http_basic_authentication: [ENV['PACKAGECLOUD_TOKEN'], ''])
rescue => e
  puts e.message
end

10.times do
  puts "Checking #{url}"
  data = JSON.load(poll(url))
  actual = data['version'].split('.').last
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
