#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

def run(cmd)
  puts "$ #{cmd}"
  system cmd || abort
end

netrc = File.expand_path('~/.netrc')

File.write netrc, <<~str
machine github.com
  login #{ENV['GITHUB_TOKEN']}
str
File.chmod 0600, netrc

mkdir 'tmp'
run   'git clone https://github.com/travis-ci/dpl_test.git tmp/dpl_test_heroku'
chdir 'tmp/dpl_test_heroku'
run   'git checkout -B engine_yard'

File.write 'config.ru', <<~str
  require 'rack'
  run ->(env) {  [200, { 'Content-type' => 'text/plain' }, ['#{ENV['ID']}']] }
str

run "git commit -am 'test dpl Engine Yard #{ENV['ID']}'"
run 'git push -f origin/engine_yard'

chdir '../..'
