#!/usr/bin/env ruby

require 'json'
require 'net/http'
require 'securerandom'
require 'optparse'

token = ENV['TRAVIS_API_TOKEN']

ARGV.options do |o|
  o.on('-t', '--token TOKEN') { |obj| token = obj }
  o.parse!
end

uri = URI.parse('https://api.travis-ci.org/repo/travis-ci%2Fdpl/requests')

body = {
  request: {
    branch: 'sf-dpl2',
    message: "test dpl github releases #{Time.now}",
    config: {
      import: "./.travis/providers/github_releases.yml",
      env: {
        ID: SecureRandom.hex
      }
    }
  }
}

http = Net::HTTP.new(uri.host, uri.port)
http.use_ssl = true

req = Net::HTTP::Post.new(uri.path)
req['Authorization'] = "token #{token}"
req['Content-Type'] = 'application/json'
req['Travis-API-Version'] = '3'
req.body = JSON.dump(body)

res = http.request(req)
p res.code.to_i
# puts res.body
