#!/usr/bin/env ruby

require 'net/http'
require 'uri'

# not sure why, but strangely, this doesn't list the gem, as it would, locally
# puts Net::HTTP.get(URI.parse('http://localhost:9292/'))

uri  = URI.parse('http://localhost:9292/gems/dpl_test')
http = Net::HTTP.new(uri.host, uri.port)
req  = Net::HTTP::Get.new(uri.path)

5.times do
  res  = http.request(req)
  puts 'GET http://localhost:9292/gems/dpl_test'
  puts "Status: #{res.code}"
  exit 0 if res.code.to_i == 200
  sleep 3
end

abort 'failed'
