source 'https://rubygems.org'
ruby '> 2.1' # 2.2 and up

gemspec name: 'dpl', path: 'gemspecs'
gemspec name: 'dpl-anynines', path: 'gemspecs'
gemspec name: 'dpl-atlas', path: 'gemspecs'
gemspec name: 'dpl-azure_webapps', path: 'gemspecs'
gemspec name: 'dpl-bintray', path: 'gemspecs'
gemspec name: 'dpl-bitballoon', path: 'gemspecs'
gemspec name: 'dpl-bluemix_cloud_foundry', path: 'gemspecs'
gemspec name: 'dpl-boxfuse', path: 'gemspecs'
gemspec name: 'dpl-cargo', path: 'gemspecs'
gemspec name: 'dpl-catalyze', path: 'gemspecs'
gemspec name: 'dpl-chef_supermarket', path: 'gemspecs'
gemspec name: 'dpl-cloud66', path: 'gemspecs'
gemspec name: 'dpl-cloud_files', path: 'gemspecs'
gemspec name: 'dpl-cloud_foundry', path: 'gemspecs'
gemspec name: 'dpl-code_deploy', path: 'gemspecs'
gemspec name: 'dpl-deis', path: 'gemspecs'
gemspec name: 'dpl-elastic_beanstalk', path: 'gemspecs'
gemspec name: 'dpl-engine_yard', path: 'gemspecs'
gemspec name: 'dpl-firebase', path: 'gemspecs'
gemspec name: 'dpl-gae', path: 'gemspecs'
gemspec name: 'dpl-gcs', path: 'gemspecs'
gemspec name: 'dpl-hackage', path: 'gemspecs'
gemspec name: 'dpl-hephy', path: 'gemspecs'
gemspec name: 'dpl-heroku', path: 'gemspecs'
gemspec name: 'dpl-lambda', path: 'gemspecs'
gemspec name: 'dpl-launchpad', path: 'gemspecs'
gemspec name: 'dpl-npm', path: 'gemspecs'
gemspec name: 'dpl-openshift', path: 'gemspecs'
gemspec name: 'dpl-ops_works', path: 'gemspecs'
gemspec name: 'dpl-packagecloud', path: 'gemspecs'
gemspec name: 'dpl-pages', path: 'gemspecs'
gemspec name: 'dpl-puppet_forge', path: 'gemspecs'
gemspec name: 'dpl-pypi', path: 'gemspecs'
gemspec name: 'dpl-releases', path: 'gemspecs'
gemspec name: 'dpl-rubygems', path: 'gemspecs'
gemspec name: 'dpl-s3', path: 'gemspecs'
gemspec name: 'dpl-scalingo', path: 'gemspecs'
gemspec name: 'dpl-script', path: 'gemspecs'
gemspec name: 'dpl-snap', path: 'gemspecs'
gemspec name: 'dpl-surge', path: 'gemspecs'
gemspec name: 'dpl-testfairy', path: 'gemspecs'
gemspec name: 'dpl-transifex', path: 'gemspecs'

# gem 'cl', git: 'https://github.com/svenfuchs/cl', ref: 'sf-v0.1.0'
# gem 'cl', path: '../../cl'
gem 'cl'

group :test do
  gem 'memfs'
  gem 'rspec'
  gem 'webmock'
end
