#!/usr/bin/env ruby

require 'open-uri'

expected = ENV['ID']
url = 'https://dpl-test-bf4fc.firebaseapp.com/'

def poll(url)
  uri = URI.parse(url)
  actual = uri.read
rescue OpenURI::HTTPError => e
end

20.times do
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
