#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test'
mkdir_p dir
chdir dir

File.write 'dpl-test.csproj', <<~str
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Version>1.0.0-#{ENV['ID']}</Version>
	</PropertyGroup>
</Project>
str

system 'dotnet pack -o ./'
