#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = ENV['ID']
url = "https://www.myget.org/F/dpl-nuget-test/api/v2/package/dpl-test/1.0.0-#{ENV['ID']}"

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

10.times do
  puts "Checking #{url}"
  exit 0 if poll(url)
  sleep 5
end

abort 'failed'
