#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test'
mkdir_p dir
chdir dir

File.write 'Gemfile', <<~str
  source 'https://rubygems.org'
  ruby '2.6.3'
  gem 'rack'
str

File.write 'Gemfile.lock', <<~str
  GEM
    remote: https://rubygems.org/
    specs:
      rack (2.0.7)

  PLATFORMS
    ruby

  DEPENDENCIES
    rack
str

File.write 'config.ru', <<~str
  require 'rack'
  run ->(env) {  [200, { 'Content-type' => 'text/plain' }, ['#{ENV['ID']}']] }
str

system 'git init'
system 'git add .'
system "git commit -m 'test dpl heroku #{Time.now}'"
