#!/usr/bin/env ruby

require 'open-uri'

expected = ENV['ID']

10.times do
  uri = URI.parse(ARGV[0])
  actual = uri.read
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
