#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test'

def write(path, content)
  mkdir_p File.dirname(path)
  File.write(path, content)
end

write "#{dir}/index.html", ENV['ID']
write "#{dir}/foo/index.html", ENV['ID']
write "#{dir}/foo/bar/index.html", ENV['ID']
