#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = ENV['ID']

10.times do
  begin
    uri = URI.parse('https://storage.googleapis.com/dpl-test/index.html')
    actual = uri.read
    puts "expected: #{expected.inspect}"
    puts "actual: #{actual.inspect}"
    exit 0 if actual == expected
    sleep 5
  rescue OpenURI::HTTPError => e
    puts e.message
    sleep 5
  end
end

abort 'failed'
