#!/usr/bin/env ruby

$stdout.sync = true

require 'open-uri'

expected = ENV['ID']
url = 'https://dpl-test.netlify.com'

def poll(url)
  uri = URI.parse(url)
  actual = uri.read
rescue OpenURI::HTTPError => e
end

20.times do
  puts "polling: #{url} ..."
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
