#!/usr/bin/env ruby

require 'open-uri'

expected = ENV['ID']

20.times do
  uri = URI.parse('http://dpl-test-app-dpl-test.apps.us-west-2.online-starter.openshift.com/')
  actual = uri.read
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
