#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test'
mkdir_p dir
chdir dir

File.write 'package.json', <<~str
  {
    "name": "dpl_test",
    "repository": "git://github.com/travis-dpl-test/dpl_test",
    "description": "testing travis ci/dpl github npm integration",
    "version": "1.0.#{ENV['TRAVIS_BUILD_NUMBER']}-#{ENV['ID']}"
  }
str
