#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test'
mkdir_p "#{dir}/foo"
chdir dir

File.write 'foo/dpl_test.rb', <<~str
  p #{ENV['ID'].inspect}
str

# version = 'v0.0.0'
version = "v0.0.#{ENV['TRAVIS_BUILD_NUMBER']}-#{ENV['ID']}"

system 'git init'
system 'git add .'
system "git commit -m 'test dpl github releases #{Time.now}'"
system "git tag -a #{version} -m 'version #{version}'"
