#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = "v0.0.#{ENV['TRAVIS_BUILD_NUMBER']}-#{ENV['ID']}"
url = 'https://api.github.com/repos/travis-ci/dpl_test/releases/latest'

def poll(url)
  json = URI.parse(url).read
  JSON.load(json)
rescue => e
  puts e.message
  {}
end

10.times do
  puts "Checking #{url}"
  actual = poll(url)['tag_name']
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
