#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']
url = 'https://raw.githubusercontent.com/travis-ci/dpl_test/test-git-push/id'

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

10.times do
  actual = poll(url).chomp
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 10
end

abort 'failed'
