#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

expected = ENV['ID']
url = "https://www.myget.org/F/dpl-test/npm/@dpl-test/dpl-test/-/@dpl-test/dpl-test-1.0.0-#{ENV['ID']}.tgz"

10.times do
  puts "Checking #{url}"
  exit 0 if poll(url)
  sleep 5
end

abort 'failed'
