#!/usr/bin/env ruby

require 'bundler/inline'
require 'fileutils'

include FileUtils

gemfile do
  gem 'engineyard-cloud-client', '~> 2.1.0'
end

def run(cmd)
  puts "$ #{cmd}"
  system(cmd) || abort
end

netrc = File.expand_path('~/.netrc')

File.write netrc, <<~str
machine github.com
  login #{ENV['GITHUB_TOKEN']}
str
File.chmod 0600, netrc

mkdir 'tmp' unless File.directory?('tmp')
run   'git clone https://github.com/travis-ci/dpl_test.git tmp/dpl_test'
chdir 'tmp/dpl_test'
run   'git checkout -B engine_yard'

File.write 'config.ru', <<~str
  require 'rack'
  run ->(env) {  [200, { 'Content-type' => 'text/plain' }, ['#{ENV['ID']}']] }
str

File.write 'id', ENV['ID']

run 'git add .'
run "git commit -m 'test dpl Engine Yard #{ENV['ID']}'"
run 'git push -f origin engine_yard'

# token = ENV['ENGINE_YARD_API_KEY']
# api = EY::CloudClient.new(token: token)
# # app = api.apps.find { |app| app.name == 'travis_dpl_test' }
# # env = app.app_environments.first
# env = api.environments.first
# instance = env.instances.first
# instance.stop
# # envs = api.resolve_app_environments(app_name: 'travis_dpl_test')
# # env = envs.one_match { envs.matches.first }
