#!/usr/bin/env ruby

require 'bundler/inline'
require 'fileutils'
# require 'net/http'
# require 'open-uri'
# require 'json'

include FileUtils

gemfile do
  gem 'engineyard-cloud-client', '~> 2.1.0'
end

def run(cmd)
  puts "$ #{cmd}"
  system(cmd) || abort
end

netrc = File.expand_path('~/.netrc')

File.write netrc, <<~str
machine github.com
  login #{ENV['GITHUB_TOKEN']}
str
File.chmod 0600, netrc

mkdir 'tmp' unless File.directory?('tmp')
run   'git clone https://github.com/travis-ci/dpl_test.git tmp/dpl_test'
chdir 'tmp/dpl_test'
run   'git checkout -B engine_yard'

File.write 'config.ru', <<~str
  require 'rack'
  run ->(env) {  [200, { 'Content-type' => 'text/plain' }, ['#{ENV['ID']}']] }
str

File.write 'id', ENV['ID']

run 'git add .'
run "git commit -m 'test dpl Engine Yard #{ENV['ID']}'"
run 'git push -f origin engine_yard'


# def headers
#   { 'X-EY-TOKEN' => ENV['ENGINEYARD_TOKEN'] }
# end
#
# def servers
#   uri = URI.parse('https://api.engineyard.com/servers')
#   data = JSON.parse(uri.read(headers))
#   data['servers']
# end
#
# servers.each do |server|
#   uri = URI.parse("https://api.engineyard.com/servers/#{server['id']}/stop")
#   http = Net::HTTP.new(uri.host)
#   http.set_debug_output($stdout)
#   http.put(uri.path, '', headers)
# end
