#!/usr/bin/env ruby

require 'fileutils'
require 'net/http'
require 'open-uri'
require 'json'

include FileUtils

def run(cmd)
  puts "$ #{cmd}"
  system(cmd) || abort
end

def headers
  {
    'X-EY-TOKEN' => ENV['ENGINEYARD_TOKEN'],
    'Content-Type' => 'application/json',
    'Accept' => 'application/vnd.engineyard.v3+json',
  }
end

def servers
  uri = URI.parse('https://api.engineyard.com/servers')
  data = JSON.parse(uri.read(headers))
  data['servers']
end

servers.each do |server|
  run "EY_TOKEN=$ENGINEYARD_TOKEN ./ey servers start #{server['provisioned_id']}"
end


netrc = File.expand_path('~/.netrc')

File.write netrc, <<~str
machine github.com
  login #{ENV['GITHUB_TOKEN']}
str
File.chmod 0600, netrc

mkdir 'tmp' unless File.directory?('tmp')
run   'git clone https://github.com/travis-ci/dpl_test.git tmp/dpl_test'
chdir 'tmp/dpl_test'
run   'git checkout -B engine_yard'

File.write 'config.ru', <<~str
  require 'rack'
  run ->(env) {  [200, { 'Content-type' => 'text/plain' }, ['#{ENV['ID']}']] }
str

File.write 'id', ENV['ID']

run 'git add .'
run "git commit -m 'test dpl Engine Yard #{ENV['ID']}'"
run 'git push -f origin engine_yard'

