#!/usr/bin/env ruby

require 'open-uri'

expected = ENV['ID']

20.times do
  uri = URI.parse('http://ec2-3-219-122-248.compute-1.amazonaws.com/')
  actual = uri.read
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
