#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = ENV['ID']
url = 'https://s3.amazonaws.com/travis-dpl-test/dpl_test'

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

10.times do
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
