#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']
url = 'https://dpl-test-244917.appspot.com/'

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

40.times do
  actual = poll(url).chomp
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
