#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

def run(cmd)
  puts "$ #{cmd}"
  system(cmd) || abort
end

mkdir_p 'tmp/dpl_test'
chdir 'tmp/dpl_test'
run 'git init .'

File.write 'Procfile', <<~str
  web: node main.js
str

File.write 'package.json', <<~str
  {
    "name": "dpl-test",
    "private": true
  }
str

File.write 'main.js', <<~str
  const http = require('http');

  const hostname = '127.0.0.1';
  const port = process.env.PORT || 8080;

  const server = http.createServer((req, res) => {
    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('#{ENV['ID']}');
  });

  server.listen(port, hostname, () => {
    console.log(`Server running at http://${hostname}:${port}/`);
  });
str
