#! /usr/bin/env bash
if [ -z $TRAVIS_COMMIT_RANGE ]; then
  rake
  exit $?
fi

changes=$(git log --name-only --pretty=oneline --full-index $TRAVIS_COMMIT_RANGE | perl -ne '!/^[0-9a-f]{40}/ && /provider\/([^\/]+)(_spec)?\.rb$/ && print $1' | grep --only [^_] | sort | uniq)
status=0
if [ -n $changes ]; then
  for p in ${changes}; do
    rake spec-$p
    if [ $? -ne 0 ]; then
      status=1
    fi
  done
else
  rake
  status=$?
fi

exit $status
