#! /usr/bin/env bash
changes=$(git log --name-only --pretty=oneline --full-index $TRAVIS_COMMIT_RANGE | perl -ne '!/^[0-9a-f]{40}/ && /provider\/([^\/]+)(_spec)?\.rb$/ && print $1,"\n"')
status=0
if [ -n $changes ]; then
  for p in ${changes}; do
    rake spec-$p
    if [ $? -ne 0 ]; then
      status=1
    fi
  done
else
  rake
  status=$?
fi

exit $status
