#!/usr/bin/env ruby

require 'open-uri'
require 'json'

$stdout.sync = true

expected = "0.0.0-test.#{ENV['ID']}"
url = "https://forgeapi.puppet.com/v3/releases/dpltest-test-#{expected}"

def poll(url)
  puts "Checking #{url}"
  uri = URI.parse(url)
  data = JSON.load(uri)
  data['version']
rescue => e
  puts e.message
  nil
end

10.times do
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
