#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

dir = 'tmp/dpl_test_github_pages'
mkdir_p dir
chdir dir

File.write 'index.html', <<~str
  #{ENV['ID']}
str

system 'git init'
system 'git add .'
system "git commit -m 'test dpl github pages #{Time.now}'"
