#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']

10.times do
  uri = URI.parse('https://raw.githubusercontent.com/travis-ci/dpl_test/gh-pages/index.html')
  actual = uri.read.chomp
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
