#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']
url = 'http://dpl-test.172.17.0.2.nip.io'

def poll(url)
  URI.parse(url).read
rescue => e
  puts e.message
end

20.times do
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
