#!/usr/bin/env ruby

require 'open-uri'

$stdout.sync = true

expected = ENV['ID']
url = 'http://dpl-test.172.17.0.2.xip.io'

def poll(url)
  uri = URI.parse(url)
  actual = uri.read
rescue OpenURI::HTTPError => e
end

20.times do
  actual = poll(url)
  puts "expected: #{expected.inspect}"
  puts "actual: #{actual.inspect}"
  exit 0 if actual == expected
  sleep 5
end

abort 'failed'
