#!/usr/bin/env ruby

require 'fileutils'

include FileUtils

def run(cmd)
  puts "$ #{cmd}"
  system(cmd) || abort
end

mkdir 'tmp' unless File.directory?('tmp')
run   'git clone https://github.com/travis-ci/dpl_test.git tmp/dpl_test'
chdir 'tmp/dpl_test'

File.write 'index.html', ENV['ID']

run 'git init .'
run 'git add .'
run "git commit -m 'test dpl azure_web_apps #{ENV['ID']}'"
